version: '3.8'

services:  
    ### BACKEND ###        
    webpush-notifier:
        container_name: webpush-notifier
        image: alvidir/webpush:0.1.0-notifier
        restart: always
        ports:
            - 8080:8080
        env_file:
            - .env

    webpush-subscriber:
        container_name: webpush-subscriber
        image: alvidir/webpush:0.1.0-subscriber
        restart: always
        ports:
            - 8080:8080
        env_file:
            - .env