version: '3.8'

services:
    backend:
        container_name: webpush
        image: webpush/backend:0.1.0
        restart: always
        ports:
            - 8080:8080
            - 9090:9090
        networks: 
            - database