version: '3.8'

services:  
    ### BACKEND ###        
    notifier:
        container_name: notifier
        image: alvidir/webpush-notifier:1.0.0
        restart: always
        ports:
            - 9090:8080
        env_file:
            - .env