version: '3.8'

services:
    backend:
        container_name: webpush-rest
        image: webpush/backend:0.1.0
        restart: always
        ports:
            - 8080:8080
            - 8081:8081
        networks: 
            - database