version: '3.8'

services:  
    ### BACKEND ###        
    webpush-notifier:
        container_name: webpush-notifier
        image: alvidir/webpush-notifier:1.0.0
        restart: always
        ports:
            - 8080:8080
        env_file:
            - .env